version: "3"

services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/node
      - '/node/node_modules'
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql:latest
    environment: 
      - MYSQL_DATABASE=test
      - MYSQL_USER=hugo
      - MYSQL_PASSWORD=hugo
      - MYSQL_ROOT_PASSWORD=hugo

    